# Generated by Django 4.1.2 on 2022-10-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
