# Generated by Django 4.1.2 on 2022-10-21 19:21

from django.db import migrations, models
import products.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='img.png', null=True, upload_to=products.models.products.upload_to),
        ),
    ]
