# Generated by Django 4.1.2 on 2022-10-29 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_ampunt_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='ampunt_sell',
            new_name='amunt_sell',
        ),
    ]
