# Generated by Django 4.1.2 on 2022-10-23 14:24

from django.db import migrations, models
import products.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='image.jpg', null=True, upload_to=products.models.products.upload_to),
        ),
    ]
