# Generated by Django 4.1.2 on 2022-10-21 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales_products.models.sales


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_sale', models.IntegerField(default=sales_products.models.sales.generate_id, editable=False)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order_status', models.BooleanField(default=True)),
                ('date_sale', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vender Produto',
                'verbose_name_plural': 'Vender Produtos',
                'db_table': 'sales',
                'ordering': ('-date_sale',),
            },
        ),
    ]
