# Generated by Django 4.1.2 on 2022-10-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('sales_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='product',
            field=models.ManyToManyField(to='cart.cart'),
        ),
    ]
