# Generated by Django 4.1.2 on 2022-10-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saldo',
                'verbose_name_plural': 'Saldos',
                'db_table': 'balance',
                'ordering': ('-date_order',),
            },
        ),
    ]
