# Generated by Django 4.1.2 on 2022-10-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellproduct',
            old_name='products',
            new_name='cart_product',
        ),
    ]
