# Generated by Django 4.1.2 on 2022-10-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('sales_products', '0002_remove_sellproduct_product_sellproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='cart.cart'),
        ),
    ]
