# Generated by Django 4.1.2 on 2022-10-31 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0002_rename_products_sellproduct_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sellproduct',
            name='unit_price',
        ),
    ]
