# Generated by Django 4.1.2 on 2022-10-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0003_alter_sellproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='product',
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
