# Generated by Django 4.1.2 on 2022-10-21 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0003_alter_sellproduct_amount_alter_sellproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellproduct',
            options={'ordering': ('-date_sale',), 'verbose_name': 'Produtos vendidos', 'verbose_name_plural': 'Produtos vendidos'},
        ),
        migrations.AlterField(
            model_name='balance',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 21, 3, 52, 12, 495319)),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=9, null=True),
        ),
    ]
