# Generated by Django 4.1.2 on 2022-10-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0003_remove_sellproduct_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=9, null=True),
        ),
    ]
