# Generated by Django 4.1.2 on 2022-10-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0004_sellproduct_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
