# Generated by Django 4.1.2 on 2022-10-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0004_alter_sellproduct_options_alter_balance_date_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
