# Generated by Django 4.1.2 on 2022-10-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0005_alter_balance_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='product',
            field=models.CharField(max_length=20),
        ),
    ]
