# Generated by Django 4.1.2 on 2022-10-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_image'),
        ('sales_products', '0006_alter_sellproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
