# Generated by Django 4.1.2 on 2022-10-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0007_alter_sellproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='product',
            field=models.CharField(max_length=50),
        ),
    ]
