# Generated by Django 4.1.2 on 2022-10-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0008_alter_sellproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
