# Generated by Django 4.1.2 on 2022-10-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_image'),
        ('sales_products', '0009_alter_sellproduct_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
