# Generated by Django 4.1.2 on 2022-10-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_products', '0010_alter_sellproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='amoun_week',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='balance',
            name='amount_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='balance',
            name='amount_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=9, null=True),
        ),
    ]
