# Generated by Django 4.1.2 on 2022-10-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantidade de produtos'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='valor_total',
            field=models.CharField(default='0.00', help_text='Valor total a ser pago', max_length=10),
        ),
    ]
