# Generated by Django 4.1.2 on 2022-10-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total a ser pago', max_digits=100),
        ),
    ]
