# Generated by Django 4.1.2 on 2022-10-25 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models.user_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.IntegerField(blank=True, db_column='idade', default=0, null=True)),
                ('cidade', models.CharField(blank=True, db_column='cidade', max_length=20, null=True)),
                ('contato', models.CharField(blank=True, db_column='contato', max_length=11, null=True)),
                ('endereco', models.CharField(blank=True, db_column='endereco', max_length=20, null=True)),
                ('numero_casa', models.IntegerField(blank=True, db_column='numero_casa', null=True)),
                ('data_nascimento', models.DateField(blank=True, db_column='data_nascimento', null=True)),
                ('imagem_perfil', models.ImageField(blank=True, db_column='imagem_perfil', default='usuario.png', null=True, upload_to=users.models.user_model.upload_to)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, db_column='data_cadastro')),
                ('data_update', models.DateTimeField(auto_now=True, db_column='data_update')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'profile_user',
            },
        ),
    ]
