# Generated by Django 4.1.2 on 2022-10-21 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models.profile


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_nome', models.CharField(max_length=100)),
                ('photo_user', models.FileField(blank=True, null=True, upload_to=users.models.profile.upload_to)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('email', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'db_table': 'profile_user',
            },
        ),
    ]
